//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        public string AdjustmentCode { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> QuantOnHand { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public string Username { get; set; }
        public string Reason { get; set; }
        public string ApprovedBy { get; set; }
    
        public virtual StationeryCatalogue StationeryCatalogue { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
