//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignRole
    {
        public string AssignRoleCode { get; set; }
        public string TemporaryRoleCode { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string AssignedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
