//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retrieval
    {
        public string RetrievalCode { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
    
        public virtual StationeryCatalogue StationeryCatalogue { get; set; }
    }
}
