//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationeryCatalogue
    {
        private string text1;
        private string text2;
        private string text3;
        private int v;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StationeryCatalogue()
        {
            this.Adjustments = new HashSet<Adjustment>();
            this.DisbursementDetails = new HashSet<DisbursementDetail>();
            this.PODetails = new HashSet<PODetail>();
            this.RequestDetails = new HashSet<RequestDetail>();
            this.Retrievals = new HashSet<Retrieval>();
            this.TenderDetails = new HashSet<TenderDetail>();
        }

        public StationeryCatalogue(string text1, string text2, string text3, int v)
        {
            this.text1 = text1;
            this.text2 = text2;
            this.text3 = text3;
            this.v = v;
        }

        public string ItemCode { get; set; }
        public string CategoryCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> ReorderQuantity { get; set; }
        public string MeasureUnit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Supplier1 { get; set; }
        public string Supplier2 { get; set; }
        public string Supplier3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjustment> Adjustments { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisbursementDetail> DisbursementDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PODetail> PODetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestDetail> RequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retrieval> Retrievals { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supplier Supplier4 { get; set; }
        public virtual Supplier Supplier5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenderDetail> TenderDetails { get; set; }
    }
}
